name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  
      - name: Install dependencies
        run: npm install cypress
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML report
          path: cypress/reports/html